steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=web"]
    args: ["get", "."]
    id: "go-get"

  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=web"]
    args: ["install", "-ldflags", "-X main.buildrevision=$SHORT_SHA", "."]
    id: "go-install"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/phonic-www-prod:$SHORT_SHA", "-t", "gcr.io/$PROJECT_ID/phonic-www-prod:latest", "."]
    id: "docker-build"

  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "/workspace/kubernetes/phonic-deployment-bootstrap.yaml"]
#    args: ['set', 'image', 'deployment/phonic-www-prod', 'phonic-www-prod=gcr.io/$PROJECT_ID/phonic-www-prod:$SHORT_SHA']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=phonic-test'
    id: "kubectl-apply"

images: ["gcr.io/$PROJECT_ID/phonic-www-prod:$SHORT_SHA", "gcr.io/$PROJECT_ID/phonic-www-prod:latest"]
